name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request, push]
    
      
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "The repository cloned"
        
      - name: Installing node
        uses: actions/setup-node@v6.4.0
      - run: echo "Node installed"
      
      - name: Installing dependencies
        run: npm install
      - run: echo "Dependencies installed"
      
      - name: Testing
        run: npm test

      - name: Linting
        uses: sibiraj-s/action-eslint@v4
        
            
      
